### ISSUE TITLE
Exports do not have 'embeddings' encoded properly

### ISSUE THREAD

**Issue by steveswinsburg** [orionhealth/XBDD#46]
Through a GET request it is possible to export the data from a report. There is no UI control for this yet.
For example: `https://xbdd.yourserver.com/xbdd/rest/reports/[product]/[version]/[build]`

However the 'embeddings' in this file are not formatted correctly and when you import this file it will fail with:
```
java.lang.ClassCastException: java.lang.String cannot be cast to com.mongodb.DBObject
	at xbdd.webapp.resource.feature.Report.embedSteps(Report.java:209)
	at xbdd.webapp.resource.feature.Report.putReport(Report.java:353)
	at xbdd.webapp.resource.feature.Report.uploadFile(Report.java:426)
```

The exported file contains:
```
 "embeddings": ["x1.0505p16x1.7f32p16-x1.a823p16-x1.b1e1p16-x1.934fp16-x1.948p16x1.ac99p16x1.b5dcp16"],

```

A real file, and what XBDD expects, contains:
```
"embeddings": [
              {
                "data": "iVBORw0KGgoAAAANSUhEUgAABQAAAAOKCAYAAADEH/1zAAAgAElEQVR4nOzdeVxU9cIGcLq9do0Wtaw016S9tM2yrma3W7ewLK1sL5NA9n0XlFUUBHHDlVRccwvFBXEDUVRwZ5UdZAcRZFRAgXneP7icGGYfhkV4vp/P8/ncOdv8zgye952ns+iAiIiIiIiIiIiIeiydrh4AERERERERERERdRwWgERERERERERERD0YC0AiIiIiIiIiIqIejAUgERERERERERFRD8YCkIiIiIiIiIiIqAdjAUhERERERERERNSDsQAkIiIiIiIiIiLqwVgAEhERERERUbdy40Y1cnIykZqahKSkS/dUUlOTkJOThZqaG71ifxmG6dxocowBWAASERERERFRN1JSUowrV1JRU3MDDQ0NXT0ctTU0NKCm5gbS09NQWlqsdPl7fX+JOlNS0qWuHkKXU/cY04IFIBEREREREXULIlENrlxJRWNjY1cPpd0aGxtx5UoKRKIaucv0pP0l6gwsAP+myjGmNRaARERERERE1C1ocllbd9Z8aW+W3Pk9bX+JOhoLQEnKjjGtsQAkIiIilZUV5yMhPhbHjkUh6tABhmE6OceORSEhPhZlxfldfTgg6hApKYloampq93YKCwuRkpKshRG1T2NjI1JSkuTO19b+EvUWLAAlKTvGtMYCkIiIiFSSnnYJx2MOoywvEXeqsgBRLsMwnZw7VVkoy7+ME7GHkZHGH0HU82jrx72PjxeMjAxQW1urle21h6J9YplBpB7+m5Gm6mfCApCIiIiUqigtwPGYw7jL4o9hukXuVmXh+PFDqCgr7OrDA5FWtefH/d27dxERsRv29rYwNJwBQ8MZMDc3wdq1oaiurtbiKNXDApBIe/hvRhoLQCIiItKahPhYlOUldnnpwTDM3ynLS8TZ+BNdfXigXqC2thYbN4YhNHQ1qqqqADQ/hXL
<snip>
```

**Comment by steveswinsburg** [comment]
Looking through the mongo db, it looks like the data is stored this way.

**Comment by ryan-rushton** [comment]
That is essentially a reference to the encoded file and there is an API to get it. When we do exports we would need to hydrate that.
